include = c:\w\h

!ifndef SIERRA
target	= sci.exe
targetub = sciub.exe
debugOpt = /dDEBUG
bannerOpt=
!else
target	= sierra.exe
targetub = sierraub.exe
debugOpt = 
bannerOpt= -Q
!endif

debugObjs = &
	asm2cpp.obd &
	math.obd &
	msg.obd &
	dos.obd &
	pmachine.obd &
	sci.obd	&
	scid.obd	&
	hotkey.obj

objects = &
	array.obj &
	audio.obj &
	audioa.obj &
	audiod.obj &
	blob.obj &
	bufferd.obj &
	celasm.obj &
	celobj.obj &
	celobj1.obj &
	celobj2.obj &
	celobja.obj &
	config.obj &
	criterr.obj &
	criterrd.obj &
	cursord.obj &
	dcomp.obj &
	dialog.obj &
	drawlist.obj &
	errormgr.obj &
	event.obj &
	eventd.obj &
	except.obj &
	fault.obj &
	font.obj &
	fonti.obj &
	graph.obj &
	graphmgr.obj &
	graphmd.obj &
	info.obj &
	integ.obj &
	intflag.obj &
	intrpt.obj &
	kbdd.obj &
	kbdmgr.obj &
	kbdmgrd.obj &
	kernel.obj &
	language.obj &
	line.obj &
	list.obj &
	magnify.obj &
	memid.obj &
	memmgr.obj &
	memmgrd.obj &
	memmgre.obj &
	memtype.obj &
	message.obj &
	midi.obj &
	millisec.obj &
	mono.obj &
	motion.obj &
	mouse.obj &
	moused.obj &
	movdsp.obj &
	movie.obj &
	msgd.obj &
	new.obj &
	newroom.obj &
	object.obj &
	palette.obj &
	palmgrd.obj &
	palmgri.obj &
	picture.obj &
	plane.obj &
	platfrmd.obj &
	playvmd.obj &
	plist.obj &
	polygon.obj &
	ratio.obj &
	rect.obj &
	rectlist.obj &
	remap.obj &
	resource.obj &
	restype.obj &
	robot.obj &
	savegame.obj &
	screen.obj &
	script.obj &
	select.obj &
	sendstac.obj &
	shiftpal.obj &
	shwstyle.obj &
	si.obj &
	silist.obj &
	sound.obj &
	soundd.obj &
	stampver.obj &
	string.obj &
	sync.obj &
	table.obj &
	textid.obj &
	time.obj &
	timed.obj &
	vga.obj &
	video.obj &
	vocab.obj &
	vmd.obj	&
	vmdbase.obj &
	vmdcache.obj &
	vmddecmp.obj &
	vmdmore.obj &
	vmdimd.obj	&
	vmdloop.obj &
	vmdsound.obj &
	vmdtrack.obj &
	vmdvesa.obj &
	vmdview.obj &
	window.obj

#	breakpt.obd &
#	debug.obd &
#	debugdsp.obd &
#	debugmnu.obd &

$(target) : $(debugObjs) $(objects) 
	*wlink name $(targetub) system dos4g option map option stack=16k &
		debug all file {$(debugObjs)} &
		debug file {$(objects)}	 l suvbelib, spmode
	c:\watcom\bin\4gwbind c:\watcom\bin\4gwpro.exe $(targetub) $(target) $(bannerOpt) -V
