#if !defined(SCIDLL_H)
#define SCIDLL_H

#define	DLL_INIT					1
#define	DLL_TICK					3
#define	DLL_SOUND_A				4
#define	DLL_SOUND_B				5
#define	DLL_SOUND_C				6
#define	DLL_SOUND_D				7
#define	DLL_SOUND_E				8
#define	DLL_SOUND_F				9
#define	DLL_SOUND_G				10
#define	DLL_SET_TYPE			11
#define	DLL_OPEN_SND			12
#define	DLL_CLOSE_SND			13
#define	DLL_TICK_SET 			14
#define	DLL_SET_CHECK_TIME 	15
#define	DLL_END_CHECK_TIME 	16
#define	DLL_WEP 					17

#endif
