//	sciglobs.hpp
//		sci global variables identifiers

#ifndef SCIGLOBS_HPP
#define SCIGLOBS_HPP

const	g_ego						= 0;
const	g_theGame				= 1;
const	g_curRoom				= 2;
const	g_speed					= 3;
const	g_quit					= 4;
const	g_cast					= 5;
const	g_regions				= 6;
const	g_timers					= 7;
const	g_sounds					= 8;
const	g_inventory				= 9;
const	g_addToPics				= 10;
const	g_curRoomNum			= 11;
const	g_prevRoomNum			= 12;
const	g_newRoomNum			= 13;
const	g_debugOn				= 14;
const	g_score					= 15;
const	g_possibleScore		= 16;
const	g_showStyle				= 17;
const	g_aniInterval			= 18;
const	g_theCursor				= 19;
const	g_normalCursor			= 20;
const	g_waitCursor			= 21;
const	g_userFont				= 22;
const	g_smallFont				= 23;
const	g_lastEvent				= 24;
const	g_modelessDialog		= 25;
const	g_bigFont				= 26;
const	g_version				= 27;
const	g_locales				= 28;
const	g_curSaveDir			= 29;
const	g_aniThreshold			= 30;
const	g_perspective			= 31;
const	g_features				= 32;
const	g_sortedFeatures		= 33;
const	g_useSortedFeatures	= 34;
const	g_egoBlindSpot			= 35;
const	g_overlays				= 36;
const	g_doMotionCue			= 37;
const	g_systemWindow			= 38;
const	g_demoDialogTime		= 39;
const	g_currentPalette		= 40;
const	g_modelessPort			= 41;
const	g_sysLogPath			= 42;
const	g_endSysLogPath		= 62;
const	g_gameControls			= 63;
const	g_ftrInitializer		= 64;
const	g_doVerbCode			= 65;
const	g_firstSaidHandler	= 66;
const	g_useObstacles			= 67;
const	g_theMenuBar			= 68;
const	g_theIconBar			= 69;
const	g_mouseX					= 70;
const	g_mouseY					= 71;
const	g_keyDownHandler		= 72;
const	g_mouseDownHandler	= 73;
const	g_directionHandler	= 74;
const	g_gameCursor			= 75;
const	g_lastVolume			= 76;
const	g_pMouse					= 77;
const	g_theDoits				= 78;
const	g_eatMice				= 79;
const	g_user					= 80;
const	g_syncBias				= 81;
const	g_theSync				= 82;
const	g_cDAudio				= 83;
const	g_fastCast				= 84;
const	g_inputFont				= 85;
const	g_tickOffset			= 86;
const	g_howFast				= 87;
const	g_gameTime				= 88;
const	g_lastSysGlobal		= 99;

#endif
