
				Listing of 0.sc:	[script 0]


LINE/	OFFSET	CODE				NAME
LABEL	(HEX)

----------------------
-------- Heap --------
----------------------

		    0	word	$33a


Variables:
		    2	word	$64
		    4	word	$0
		    6	word	$0
		    8	word	$0
		    a	word	$0
		    c	word	$0
		    e	word	$0
		   10	word	$0
		   12	word	$0
		   14	word	$0
		   16	word	$0
		   18	word	$0
		   1a	word	$0
		   1c	word	$0
		   1e	word	$0
		   20	word	$0
		   22	word	$0
		   24	word	$0
		   26	word	$0
		   28	word	$0
		   2a	word	$0
		   2c	word	$0
		   2e	word	$0
		   30	word	$1
		   32	word	$4
		   34	word	$0
		   36	word	$7fff
		   38	word	$1
		   3a	word	$0
		   3c	word	$0
		   3e	word	$0
		   40	word	$0
		   42	word	$0
		   44	word	$0
		   46	word	$0
		   48	word	$0
		   4a	word	$0
		   4c	word	$ffff
		   4e	word	$0
		   50	word	$0
		   52	word	$0
		   54	word	$0
		   56	word	$0
		   58	word	$0
		   5a	word	$0
		   5c	word	$0
		   5e	word	$0
		   60	word	$0
		   62	word	$0
		   64	word	$0
		   66	word	$0
		   68	word	$0
		   6a	word	$0
		   6c	word	$0
		   6e	word	$0
		   70	word	$0
		   72	word	$0
		   74	word	$0
		   76	word	$0
		   78	word	$0
		   7a	word	$0
		   7c	word	$0
		   7e	word	$0
		   80	word	$0
		   82	word	$0
		   84	word	$0
		   86	word	$0
		   88	word	$0
		   8a	word	$1
		   8c	word	$0
		   8e	word	$0
		   90	word	$0
		   92	word	$0
		   94	word	$0
		   96	word	$0
		   98	word	$0
		   9a	word	$0
		   9c	word	$0
		   9e	word	$0
		   a0	word	$0
		   a2	word	$3c
		   a4	word	$0
		   a6	word	$0
		   a8	word	$0
		   aa	word	$0
		   ac	word	$0
		   ae	word	$0
		   b0	word	$0
		   b2	word	$0
		   b4	word	$0
		   b6	word	$0
		   b8	word	$1
		   ba	word	$0
		   bc	word	$0
		   be	word	$0
		   c0	word	$2
		   c2	word	$0
		   c4	word	$140
		   c6	word	$c8
		   c8	word	$13f
		   ca	word	$c7



Object: DummyEgo            
		(properties)
		   cc	prop  $1234	(-objID-)
		   ce	prop  $4f  	(-size-)
		   d0	ofs   $a   	(-propDict-)
		   d2	ofs   $a   	(-methDict-)
		   d4	prop  $0   	(-classScript-)
		   d6	prop  $ffff	(-script-)
		   d8	prop  $47  	(-super-)
		   da	prop  $0   	(-info-)
		   dc	text  $2f0 	(name)
		   de	prop  $0   	(scratch)
		   e0	prop  $0   	(heading)
		   e2	prop  $0   	(noun)
		   e4	prop  $0   	(case)
		   e6	prop  $ffff	(modNum)
		   e8	prop  $0   	(nsLeft)
		   ea	prop  $0   	(nsTop)
		   ec	prop  $0   	(nsRight)
		   ee	prop  $0   	(nsBottom)
		   f0	prop  $6789	(sightAngle)
		   f2	prop  $0   	(actions)
		   f4	prop  $0   	(onMeCheck)
		   f6	prop  $0   	(state)
		   f8	prop  $0   	(approachX)
		   fa	prop  $0   	(approachY)
		   fc	prop  $0   	(approachDist)
		   fe	prop  $0   	(_approachVerbs)
		  100	prop  $0   	(plane)
		  102	prop  $0   	(x)
		  104	prop  $0   	(y)
		  106	prop  $0   	(z)
		  108	prop  $80  	(scaleX)
		  10a	prop  $80  	(scaleY)
		  10c	prop  $80  	(maxScale)
		  10e	prop  $0   	(scaleType)
		  110	prop  $0   	(priority)
		  112	prop  $0   	(fixPriority)
		  114	prop  $0   	(inLeft)
		  116	prop  $0   	(inTop)
		  118	prop  $0   	(inRight)
		  11a	prop  $0   	(inBottom)
		  11c	prop  $0   	(useInsetRect)
		  11e	prop  $ffff	(view)
		  120	prop  $0   	(loop)
		  122	prop  $0   	(cel)
		  124	prop  $0   	(bitmap)
		  126	prop  $2   	(yStep)
		  128	prop  $5021	(signal)
		  12a	prop  $0   	(lsLeft)
		  12c	prop  $0   	(lsTop)
		  12e	prop  $0   	(lsRight)
		  130	prop  $0   	(lsBottom)
		  132	prop  $0   	(brLeft)
		  134	prop  $0   	(brTop)
		  136	prop  $0   	(brRight)
		  138	prop  $0   	(brBottom)
		  13a	prop  $0   	(scaleSignal)
		  13c	prop  $0   	(magnifier)
		  13e	prop  $80  	(oldScaleX)
		  140	prop  $6   	(cycleSpeed)
		  142	prop  $0   	(script)
		  144	prop  $0   	(cycler)
		  146	prop  $0   	(timer)
		  148	prop  $0   	(detailLevel)
		  14a	prop  $0   	(scaler)
		  14c	prop  $0   	(code)
		  14e	prop  $8000	(illegalBits)
		  150	prop  $0   	(xLast)
		  152	prop  $0   	(yLast)
		  154	prop  $3   	(xStep)
		  156	prop  $302 	(origStep)
		  158	prop  $6   	(moveSpeed)
		  15a	prop  $0   	(blocks)
		  15c	prop  $0   	(baseSetter)
		  15e	prop  $0   	(mover)
		  160	prop  $0   	(looper)
		  162	prop  $0   	(viewer)
		  164	prop  $0   	(avoider)
		  166	prop  $0   	(robot)
		  168	prop  $0   	(edgeHit)

Object: Bench               
		(properties)
		  16a	prop  $1234	(-objID-)
		  16c	prop  $11  	(-size-)
		  16e	ofs   $c   	(-propDict-)
		  170	ofs   $2e  	(-methDict-)
		  172	prop  $0   	(-classScript-)
		  174	prop  $77  	(-script-)
		  176	prop  $50  	(-super-)
		  178	prop  $8000	(-info-)
		  17a	text  $309 	(name)
		  17c	prop  $0   	(scratch)
		  17e	prop  $0   	(script)
		  180	prop  $1   	(printLang)
		  182	prop  $3   	(_detailLevel)
		  184	prop  $0   	(panelObj)
		  186	prop  $0   	(panelSelector)
		  188	prop  $0   	(handsOffCode)
		  18a	prop  $0   	(handsOnCode)

Object: theGameCursor       
		(properties)
		  18c	prop  $1234	(-objID-)
		  18e	prop  $3b  	(-size-)
		  190	ofs   $34  	(-propDict-)
		  192	ofs   $34  	(-methDict-)
		  194	prop  $0   	(-classScript-)
		  196	prop  $ffff	(-script-)
		  198	prop  $31  	(-super-)
		  19a	prop  $0   	(-info-)
		  19c	text  $30f 	(name)
		  19e	prop  $0   	(scratch)
		  1a0	prop  $0   	(heading)
		  1a2	prop  $0   	(noun)
		  1a4	prop  $0   	(case)
		  1a6	prop  $ffff	(modNum)
		  1a8	prop  $0   	(nsLeft)
		  1aa	prop  $0   	(nsTop)
		  1ac	prop  $0   	(nsRight)
		  1ae	prop  $0   	(nsBottom)
		  1b0	prop  $6789	(sightAngle)
		  1b2	prop  $0   	(actions)
		  1b4	prop  $0   	(onMeCheck)
		  1b6	prop  $0   	(state)
		  1b8	prop  $0   	(approachX)
		  1ba	prop  $0   	(approachY)
		  1bc	prop  $0   	(approachDist)
		  1be	prop  $0   	(_approachVerbs)
		  1c0	prop  $0   	(plane)
		  1c2	prop  $0   	(x)
		  1c4	prop  $0   	(y)
		  1c6	prop  $0   	(z)
		  1c8	prop  $80  	(scaleX)
		  1ca	prop  $80  	(scaleY)
		  1cc	prop  $80  	(maxScale)
		  1ce	prop  $0   	(scaleType)
		  1d0	prop  $0   	(priority)
		  1d2	prop  $0   	(fixPriority)
		  1d4	prop  $0   	(inLeft)
		  1d6	prop  $0   	(inTop)
		  1d8	prop  $0   	(inRight)
		  1da	prop  $0   	(inBottom)
		  1dc	prop  $0   	(useInsetRect)
		  1de	prop  $3e6 	(view)
		  1e0	prop  $0   	(loop)
		  1e2	prop  $7   	(cel)
		  1e4	prop  $0   	(bitmap)
		  1e6	prop  $2   	(yStep)
		  1e8	prop  $5021	(signal)
		  1ea	prop  $0   	(lsLeft)
		  1ec	prop  $0   	(lsTop)
		  1ee	prop  $0   	(lsRight)
		  1f0	prop  $0   	(lsBottom)
		  1f2	prop  $0   	(brLeft)
		  1f4	prop  $0   	(brTop)
		  1f6	prop  $0   	(brRight)
		  1f8	prop  $0   	(brBottom)
		  1fa	prop  $0   	(scaleSignal)
		  1fc	prop  $0   	(magnifier)
		  1fe	prop  $80  	(oldScaleX)
		  200	prop  $0   	(hidden)

Object: theWaitCursor       
		(properties)
		  202	prop  $1234	(-objID-)
		  204	prop  $3b  	(-size-)
		  206	ofs   $36  	(-propDict-)
		  208	ofs   $36  	(-methDict-)
		  20a	prop  $0   	(-classScript-)
		  20c	prop  $ffff	(-script-)
		  20e	prop  $31  	(-super-)
		  210	prop  $0   	(-info-)
		  212	text  $31d 	(name)
		  214	prop  $0   	(scratch)
		  216	prop  $0   	(heading)
		  218	prop  $0   	(noun)
		  21a	prop  $0   	(case)
		  21c	prop  $ffff	(modNum)
		  21e	prop  $0   	(nsLeft)
		  220	prop  $0   	(nsTop)
		  222	prop  $0   	(nsRight)
		  224	prop  $0   	(nsBottom)
		  226	prop  $6789	(sightAngle)
		  228	prop  $0   	(actions)
		  22a	prop  $0   	(onMeCheck)
		  22c	prop  $0   	(state)
		  22e	prop  $0   	(approachX)
		  230	prop  $0   	(approachY)
		  232	prop  $0   	(approachDist)
		  234	prop  $0   	(_approachVerbs)
		  236	prop  $0   	(plane)
		  238	prop  $0   	(x)
		  23a	prop  $0   	(y)
		  23c	prop  $0   	(z)
		  23e	prop  $80  	(scaleX)
		  240	prop  $80  	(scaleY)
		  242	prop  $80  	(maxScale)
		  244	prop  $0   	(scaleType)
		  246	prop  $0   	(priority)
		  248	prop  $0   	(fixPriority)
		  24a	prop  $0   	(inLeft)
		  24c	prop  $0   	(inTop)
		  24e	prop  $0   	(inRight)
		  250	prop  $0   	(inBottom)
		  252	prop  $0   	(useInsetRect)
		  254	prop  $3e6 	(view)
		  256	prop  $0   	(loop)
		  258	prop  $8   	(cel)
		  25a	prop  $0   	(bitmap)
		  25c	prop  $2   	(yStep)
		  25e	prop  $5021	(signal)
		  260	prop  $0   	(lsLeft)
		  262	prop  $0   	(lsTop)
		  264	prop  $0   	(lsRight)
		  266	prop  $0   	(lsBottom)
		  268	prop  $0   	(brLeft)
		  26a	prop  $0   	(brTop)
		  26c	prop  $0   	(brRight)
		  26e	prop  $0   	(brBottom)
		  270	prop  $0   	(scaleSignal)
		  272	prop  $0   	(magnifier)
		  274	prop  $80  	(oldScaleX)
		  276	prop  $0   	(hidden)

Object: theArrowCursor      
		(properties)
		  278	prop  $1234	(-objID-)
		  27a	prop  $3b  	(-size-)
		  27c	ofs   $38  	(-propDict-)
		  27e	ofs   $38  	(-methDict-)
		  280	prop  $0   	(-classScript-)
		  282	prop  $ffff	(-script-)
		  284	prop  $31  	(-super-)
		  286	prop  $0   	(-info-)
		  288	text  $32b 	(name)
		  28a	prop  $0   	(scratch)
		  28c	prop  $0   	(heading)
		  28e	prop  $0   	(noun)
		  290	prop  $0   	(case)
		  292	prop  $ffff	(modNum)
		  294	prop  $0   	(nsLeft)
		  296	prop  $0   	(nsTop)
		  298	prop  $0   	(nsRight)
		  29a	prop  $0   	(nsBottom)
		  29c	prop  $6789	(sightAngle)
		  29e	prop  $0   	(actions)
		  2a0	prop  $0   	(onMeCheck)
		  2a2	prop  $0   	(state)
		  2a4	prop  $0   	(approachX)
		  2a6	prop  $0   	(approachY)
		  2a8	prop  $0   	(approachDist)
		  2aa	prop  $0   	(_approachVerbs)
		  2ac	prop  $0   	(plane)
		  2ae	prop  $0   	(x)
		  2b0	prop  $0   	(y)
		  2b2	prop  $0   	(z)
		  2b4	prop  $80  	(scaleX)
		  2b6	prop  $80  	(scaleY)
		  2b8	prop  $80  	(maxScale)
		  2ba	prop  $0   	(scaleType)
		  2bc	prop  $0   	(priority)
		  2be	prop  $0   	(fixPriority)
		  2c0	prop  $0   	(inLeft)
		  2c2	prop  $0   	(inTop)
		  2c4	prop  $0   	(inRight)
		  2c6	prop  $0   	(inBottom)
		  2c8	prop  $0   	(useInsetRect)
		  2ca	prop  $3e6 	(view)
		  2cc	prop  $0   	(loop)
		  2ce	prop  $7   	(cel)
		  2d0	prop  $0   	(bitmap)
		  2d2	prop  $2   	(yStep)
		  2d4	prop  $5021	(signal)
		  2d6	prop  $0   	(lsLeft)
		  2d8	prop  $0   	(lsTop)
		  2da	prop  $0   	(lsRight)
		  2dc	prop  $0   	(lsBottom)
		  2de	prop  $0   	(brLeft)
		  2e0	prop  $0   	(brTop)
		  2e2	prop  $0   	(brRight)
		  2e4	prop  $0   	(brBottom)
		  2e6	prop  $0   	(scaleSignal)
		  2e8	prop  $0   	(magnifier)
		  2ea	prop  $80  	(oldScaleX)
		  2ec	prop  $0   	(hidden)
		  2ee	word	$0



		  2f0	text
"DummyEgo"

		  2f9	text
"The game init:"

		  309	text
"Bench"

		  30f	text
"theGameCursor"

		  31d	text
"theWaitCursor"

		  32b	text
"theArrowCursor"



Fixups:
		  33a	word	$5
		  33c	word	$dc
		  33e	word	$17a
		  340	word	$19c
		  342	word	$212
		  344	word	$288




----------------------
-------- Hunk --------
----------------------

		    0	word	$100
		    2	word	$0
		    4	word	$0
		    6	word	$1
		(dispatch table)
		    8	dispatch	$16a 	(Bench)

Object: DummyEgo            
		(property dictionary)
		(method dictionary)
		    a	word	$0

Object: Bench               
		(property dictionary)
		    c	word	$1000
		    e	word	$1001
		   10	word	$1002
		   12	word	$1003
		   14	word	$1004
		   16	word	$1005
		   18	word	$1006
		   1a	word	$1007
		   1c	word	$20
		   1e	word	$8c
		   20	word	$b0
		   22	word	$59
		   24	word	$213
		   26	word	$1b5
		   28	word	$1b6
		   2a	word	$214
		   2c	word	$215
		(method dictionary)
		   2e	word	$1
		   30	word	$8e
		   32	local $3a  	(init)

Object: theGameCursor       
		(property dictionary)
		(method dictionary)
		   34	word	$0

Object: theWaitCursor       
		(property dictionary)
		(method dictionary)
		   36	word	$0

Object: theArrowCursor      
		(property dictionary)
		(method dictionary)
		   38	word	$0


Method: (Bench init)

		   3d	file
		   46	push1
		   47	lofsa	$2f9 
		   4a	push
		   4b	callk	$83  	(MonoOut)
		   4b	word	$2
		   52	lofsa	$18c 	(theGameCursor)
		   55	sag  	$13  	(theCursor)
		   5a	lofsa	$202 	(theWaitCursor)
		   5d	sag  	$15  	(waitCursor)
		   62	lofsa	$278 	(theArrowCursor)
		   65	sag  	$14  	(normalCursor)
		   6a	ldi  	$3e7 
		   6d	sag  	$16  	(userFont)
		   72	ldi  	$3e7 
		   75	sag  	$1a  	(bigFont)
		   7a	ldi  	$3e7 
		   7d	sag  	$17  	(smallFont)
		   82	pushi	$8e  
		   85	push0
		   86	&rest	$1   
		   88	super	$50  	(Game)
		   88	word	$4
		   8f	class	$39  	(Plane)
		   91	sag  	$26  	(systemPlane)
		   96	pushi	$16b 
		   99	pushi	$4   
		   9c	push0
		   9d	push0
		   9e	pushi	$140 
		   a1	pushi	$c7  
		   a4	lag  	$3   	(thePlane)
		   a6	send
		   a6	word	$c
		   ac	lofsa	$cc  	(DummyEgo)
		   af	sag  	$0   	(ego)
		   b7	pushi	$1f8 
		   ba	push1
		   bb	push
		   bf	pushi	$141 
		   c2	push1
		   c3	push1
		   c7	pushi	$1db 
		   ca	push1
		   cb	push0
		   cc	class	$45  	(User)
		   ce	send
		   ce	word	$12
		   d7	pushi	$26  
		   d9	push1
		   da	pushi	$4a  
		   df	pushi	$25  
		   e1	push1
		   e2	push0
		   e3	class	$3f  	(Print)
		   e5	send
		   e5	word	$c
		   eb	lofsa	$cc  	(DummyEgo)
		   ee	sag  	$0   	(ego)
		   f3	pushi	$216 
		   f6	push1
		   f7	push1
		   f8	self
		   f8	word	$6
		   fe	ret
		   ff	byte	$0


Fixups:
		  100	word	$7
		  102	word	$8
		  104	word	$48
		  106	word	$53
		  108	word	$5b
		  10a	word	$63
		  10c	word	$ad
		  10e	word	$ec
